build:
  verbosity: minimal

environment:
  nodejs_version: "7.0"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install

test_script:
  - node --version
  - yarn --version
  # run tests
  - (cd ./packages/devtools-source-map && yarn test)

cache:
 - node_modules
 - "%LOCALAPPDATA%\\Yarn"
